### PR TITLE
Flat and more unified look for icons and menu items

### PR DESCRIPTION
**Pull request by bonsak**
Updated the toolbar icons and included the menu items. Included a
plugin icon as well.

### CODE REVIEW

**Comment by bonsak** [comment]
All icons are now 64x64 which seems to be standard in the native c4d icons

**Comment by bonsak** [comment]
Icon for Combo Button is missing. Some work still to be done regarding readability. Just did a quick mockup in PS:
readability

**Comment by bonsak** [comment]
Mockup of menu. Still needs some tweaking.
menu-mockup

**Comment by NiklasRosenstein** [comment]
Looking good! Yes the Combo Button was also missing in the original icon set. Would be nice to have a button for it as well.

Afaik, you can't have an icon for a menu "folder" though.

**Comment by bonsak** [comment]
Your right. The folder will just get a default grey.

**Comment by NiklasRosenstein** [comment]
Very nice, thanks!

> Is it possible to have different icons for Dialog, Icons and String tables in the browser window? Or shall i leave it like it is?

I'm thinking about removing the icons from the Browser window completely, it makes no sense since they all have the same icon.

**Comment by bonsak** [comment]
Makes sense.

**Comment by NiklasRosenstein** [comment]
Only the "Source Wizard" is a bit hard to recognize.

image
image

**Comment by NiklasRosenstein** [comment]
Not a biggie right now IMHO, doesn't need to be changed just now.

**Comment by bonsak** [comment]
Agree. Diff and Compare also needs a little bit more love. Looks ok in general though.

**Pull request merged**
